# Generated by Django 5.2.17 on 2026-09-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_of_document', models.DateField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255)),
                ('originating_office', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('important_details', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('ocr_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('For Review', 'For Review'), ('Finalized', 'Finalized'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
